### ISSUE TITLE
我更新了Google浏览器产生这样的

### ISSUE THREAD

**Issue by ClaudeWilliam** [xiyouqi/Rainbow2#7]
SyntaxError: Cannot read property 'toCSS' of null
in index.less 
at http://dev.xiyouqi.cn:8080/js/vendor/less-1.7.0.min.js:16:5002
at http://dev.xiyouqi.cn:8080/js/vendor/less-1.7.0.min.js:13:7511
at d.type (http://dev.xiyouqi.cn:8080/js/vendor/less-1.7.0.min.js:13:6848)
at f (http://dev.xiyouqi.cn:8080/js/vendor/less-1.7.0.min.js:13:5749)
at r (http://dev.xiyouqi.cn:8080/js/vendor/less-1.7.0.min.js:13:6235)
at s (http://dev.xiyouqi.cn:8080/js/vendor/less-1.7.0.min.js:13:6812)
at t (http://dev.xiyouqi.cn:8080/js/vendor/less-1.7.0.min.js:13:7085)
at u (http://dev.xiyouqi.cn:8080/js/vendor/less-1.7.0.min.js:13:7590)
at Object.w.refresh (http://dev.xiyouqi.cn:8080/js/vendor/less-1.7.0.min.js:16:4845)
at http://dev.xiyouqi.cn:8080/js/vendor/less-1.7.0.min.js:16:5253

**Comment by fingnet** [comment]
![image](https://cloud.githubusercontent.com/assets/1418877/9053209/552bc634-3aa4-11e5-8878-c43273701433.png)
把这两个 Key 单击右键 Delete 掉刷新试试。
